const grammer = [ 
//	inst					op			type						regexp											argTypes															
// --------------------------------------------------------------------------------------------------------
	['REG_VAL',			null,		'valType',			"[a-z]{1}[0-9]{1}$",				[]],
	['MEM_VAL',			null,		'valType',				"[a-fA-F]{1}[0-9]{1}$",		[]],
	['MEM_VAL_ADDR',null,		'addrType',			"[a-fA-F]{1}[0-9]{1}$",			[]],
	['MEM_VAL_EXT',	null,		'valType',			"[a-fA-F]{1}[0-9]{1}$",			[]],
	['STR_TOKEN',		null,		'strType',			"[a-fA-F]{1}[0-9]{1}$",			[]],
	['NUM_TOKEN',		null,		'numType',			"[a-fA-F]{1}[0-9]{1}$",			[]],
	['INIT',				'00',		'cmd',					null,												[]],
	['INITALK',			'FE',		'cmd',					null,												[]],
	['SETR',				'01',		'setAddr',			null,												['REG_ADDR']],
	['GETR',				'6F',		'getVal',				null,												[]],
	['SAVE',				'04',		'prgCpy',				null,												[]],
	['LOAD',				'07',		'prgLd',				null,												[]],
	['PRN',					'06',		'prnBuf',				null,												[]],
	['HALT',				'00',		'cmd',					null,												[]],
	['PRAR',				'41',		'prnChar',			null,												['REG_VAL']],
	['PRAM',				'42',		'prnChar',			null,												['MEM_VAL']],
	['LD',					'08',		'setRegVal',		null,												['MEM_VAL']],
	['ST',					'09',		'setMemVal',		null,												['MEM_ADDR']],
	['LDRI',				'12',		'setRegVal',		null,												['MEM_ADDR']],
	['STRI',				'13',		'setMemVal',		null,												['MEM_ADDR']],
	['STOR',				'F5',		'setMemVal',		null,												[]],
	['LODM',				'F6',		'ldMemVal',			null,												[]],
	['POP',					'0A',		'stack',				null,												[]],
	['PUSH',				'0B',		'stack',				null,												[]],
	['CALL',				'0F',		'pointer',			null,												['MEM_VAL_ADDR']],
	['RET',					'10',		'pointer',			null,												[]],
	['PASS',				'5E',		'pointer',			null,												['MEM_VAL_ADDR']],
	['JMP',					'11',		'pointer',			null,												['MEM_VAL_ADDR']],
	['JTL',					'00',		'pointer',			null,												[]],
	['JEQ',					'14',		'pointerCond',	null,												[]],
	['JNE',					'15',		'pointerCond',	null,												['MEM_VAL', 'MEM_VAL', 'MEM_VAL_ADDR']],
	['JRNE',				'95',		'pointerCond',	null,												['MEM_VAL_ADDR']],
	['JREQ',				'97',		'pointerCond',	null,												['MEM_VAL_ADDR']],
	['CMP',					'16',		'math',					null,												[]],
	['ADD',					'0C',		'math',					null,												['MEM_VAL', 'MEM_VAL']],
	['SUB',					'0D',		'math',					null,												['MEM_VAL', 'MEM_VAL']],
	['MUL',					'05',		'math',					null,												['MEM_VAL', 'MEM_VAL']],
	['DIV',					'0E',		'math',					null,												['MEM_VAL', 'MEM_VAL']],
	['LBL',					'60',		'flow',					null,												[]],
	['LBLJMP',			'17',		'flow',					null,												['MEM_VAL_ADDR']],
	['LBSET',				'18',		'flow',					null,												['MEM_VAL']],
	['SETI',				'20',		'interupt',			null,												['MEM_VAL', 'MEM_VAL_ADDR']],
	['GETI',				'21',		'interupt',			null,												['MEM_VAL']],
	['RETI',				'EE',		'interupt',			null,												[]],
	['INPT',				'7E',		'readBuf',			null,												['MEM_VAL_EXT']],
	['OTPT',				'7F',		'writeBuf',			null,												[]],
	['RELAD',				'11',		'pointer',			null,												[]],
	['DEF',					null,		'flow',					null,												['STR_TOKEN']],
	
]

const instructionsMap = {
	byInstruction: {},
	byCode: {},
}

module.exports = grammer;